# Generated by Django 4.2.16 on 2024-11-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbconnect", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="districtdiscipline", table="district_discipline",
        ),
    ]
