# Generated by Django 4.2.16 on 2024-11-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbconnect", "0002_alter_districtdiscipline_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="school_type",
            field=models.CharField(
                choices=[("public", "Public"), ("charter", "Charter")],
                default="public",
                max_length=50,
            ),
        ),
    ]
