# Generated by Django 4.2.7 on 2024-11-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbconnect", "0003_district_school_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="districtmetrics", name="demographic_composition",
        ),
        migrations.AddField(
            model_name="districtmetrics",
            name="enrollment_asian_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="districtmetrics",
            name="enrollment_black_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="districtmetrics",
            name="enrollment_hispanic_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="districtmetrics",
            name="enrollment_multiracial_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="districtmetrics",
            name="enrollment_white_pct",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
