# Generated by Django 4.2.7 on 2024-11-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbconnect", "0004_remove_districtmetrics_demographic_composition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="districtmetrics",
            name="demographic_composition",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
